### Get all persons
GET http://localhost:3001/api/persons

### Get one Person (remember to change id)
GET http://localhost:3001/api/persons/<id>

### Add Person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Artsdsdo Hellasssss",
    "number": "050-8546015"
}

### Delete Person
DELETE http://localhost:3001/api/persons/0.9489faaad945d

### Get info
GET http://localhost:3001/info